# Application Configuration
spring:
  application:
    name: notice
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  doc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operations-sorter: alpha
      tags-sorter: alpha
      display-request-duration: true
    api-docs:
      path: /v3/api-docs
      enabled: true
    webflux:
      openapi:
        enabled: true
springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml
  packages-to-scan: com.hexagonal.notice.infrastructure.controller
  paths-to-match: /api/**

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.hexagonal.notice: DEBUG
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
