server.port=8080
spring.application.name=notice

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/notice_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG